#+TITLE: Covidm Package

This repository provides the backend for [[https://github.com/cmmid/covid-uk][this LSHTM SEI3R model]] as an R package. This is an early work in progress, please report any issues.

* System Requirements
- GNU GSL

Currently only tested on Ubuntu.

* Installation

You will first need to install the devtools package with:
#+begin_src R
install.packages("devtools")
#+end_src

After that, you an install the covidm package with:
#+begin_src R
devtools::install_github("M4rkD/covidm")
#+end_src

Once the installation completes, you can load (and attach) the package with:
#+begin_src R
library(covidm)
#+end_src

* Exported functions
Currently, only functions and data sets used by the UK.R script from the [[https://github.com/cmmid/covid-uk][LSHTM covid-uk repository]] are export by this library, despite more functions being available internally. If you require more functions exported, please open an issue and I'll be happy to export them. The intention of this approach is to only export functions which are useful.

* UK.R Script
The UK.R script is included in the repository, but not the installed package, for reference. The changes necessary to use covidm as a package have been made to the UK.R script. Note however that the script has been modified to hardcode only a single iteration of a single analysis, for two days, for demonstration purposes only. Note in particular, the file for age varying symptomatic rate has been changed.

* Limitations
Currently, this is only tested on linux systems. Please raise an issue if you're interested in a version to run on Windows or Mac.
