# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cm_backend_simulate <- function(parameters, n_run = 1L, seed = 0L) {
    .Call(`_covidm_cm_backend_simulate`, parameters, n_run, seed)
}

cm_evaluate_distribution <- function(dist_code, steps = 101L, xmin = 0, xmax = -1) {
    .Call(`_covidm_cm_evaluate_distribution`, dist_code, steps, xmin, xmax)
}

